name: Building images
run-name: ${{ github.actor }} is Building the List image 🚀
# on: [push]
on: [workflow_dispatch]
jobs:
  listbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/haydz/2024porf.git#main:list
          push: true
          tags: haydzx/list:latest
  clientbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/haydz/2024porf.git#main:client
          push: true
          tags: haydzx/inspace:latest

      # on:
      #   pull_request:
      #     # For the develop branch only.
      #     branches:
      #       - develop
      #     # Execute the action on closed (merged) PR.
      #     types:
      #       [closed]
      #     workflow_dispatch:
# docker build https://github.com/docker/rootfs.git#container:docker

